### ISSUE TITLE
Running under Capybara-webkit fails because of missing jasmineRiceReporter

### ISSUE THREAD

**Issue by bunnymatic** [launchscout/jasminerice-runner#2]
Using the new initializer, we started running our tests under Capybara-webkit.  First, the system doesn't seem to work on a Mac with Qt 4.8.2.  After reverting to Qt 4.7.0, we got the following errors:

```
Result of expression 'window.jasmineRiceReporter' [undefined] is not an object.
```

It appears that the initialization of the jasmineRiceReporter is not happening soon enough when running in Capybara.

I have a temporary workaround which is to add a file called jasminerice_reporter.js under our spec/javascripts directory which simply defines that class:

```
(function() {
  window.jasmineRiceReporter = window.jsApiReporter;
})();
```

This gets included by the spec.js.coffee file and we're off to the races.  I looked into your code and it looks like you define the reporter, but you do the assignment to window.jasmineRiceReporter in a jQuery onload block.  Maybe that's causing the issue in the headless case.

I've taken a fork but I'm not sure if i'll get to a fix soon since i do have this simple workaround.

Cheers

**Comment by superchris** [comment]
This looks like it might be a timing issue, I added a line to define jasmineRiceReporter outside of the onload block in case capybara asks for it before the onload function has run.

**Comment by bunnymatic** [comment]
Cool.  We'll give it a spin tomorrow. 

Thanks for the quick fix.
